jobapp/urls.py
from django.urls import path
from .views import *

app_name = 'jobapp'

urlpatterns = [
    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('job-admin/hello/', AdminHomeHelloView.as_view(), name='adminhomehello'),
    path('jobseeker/<int:pk>/details/',
         JobSeekerDetailView.as_view(), name='jobseekerdetail'),
    path('jobseeker/registration/', JobSeekerRegistration.as_view(),
         name='jobseekerregistration'),
    path('job/<int:pk>/apply/', JobSeekerApplyView.as_view(), name="jobapply"),
    path("login/", LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    # path('employer/registration/', EmployerRegistrationView.as_view(),
    #      name='employerregistration'),
    path('employer/myprofile/', EmployerProfileView.as_view(),
         name='employerprofile'),
    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),
    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),
    path('employer/registration/', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/profile/',AdminProfileView.as_view(),name = 'adminprofile'),





]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("jobapp.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/employertemplates/employerbase.html
{% load static %}
  <link href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' /><!-- bootstrap css -->
    <link href="{% static 'jobseekerstatic/css/style.css' %}" rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="{% static 'jobseekerstatic/css/font-awesome.css' %}" rel="stylesheet"><!-- fontawesome css -->
	<!-- //css files -->
	
	<!-- google fonts -->
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext" rel="stylesheet">
	<!-- //google fonts -->
	
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'jobapp:jobseekerhome' %}">CurrentJob<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="#">Top Jobs</a>
      <!-- <a class="nav-item nav-link active" href="#"></a> -->
      {% if request.user.is_authenticated and request.user.groups.first.name == "employer" %}
       <h5>logged in as:{{request.user}}</h5>
       <h5><a href="{% url 'jobapp:employerprofile' %}">myprofile</a></h5>
       
       <h5><a href="{% url 'jobapp:employerjobcreate' %}">Post new job</a></h5>
       
      {% else %}
        <a href="{% url 'jobapp:login' %}">login</a>
        <a class="nav-item nav-link active" href="{% url 'jobapp:employerregistration' %}">Register</a>
      {% endif %}  



    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

templates/employertemplates/employerhome.html
{% extends 'employertemplates/employerbase.html' %}
[% load static %}
{% block content %}
<h3>employer home</h3>
{% endblock %}

templates/employertemplates/employerjobcreate.html
{% extends 'employertemplates/employerbase.html' %}
[% load static %}
{% block content %}
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-info">create</button>
	

	

</form>
{% endblock %}

templates/employertemplates/employerjobdetail.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}
{% block content %}
	<h3>Job_title : {{jobobject.title}}</h3>
	<h4>Job_category : {{jobobject.category}}</h4>
	<p><img src="{{jobobject.image.url}}" width="200px;"></p>
	<li>salary : {{jobobject.salary}}</li>
	<li>skills : {{jobobject.skills}}</li>
	<li>education : {{jobobject.education}}</li>
	<li>details: {{jobobject.details}}</li>
	<li>level:{{jobobject.level}}</li>
	<hr>
	<h3>Application for this job</h3>
	<table class="table">
		<thead>
			<tr>
				<th>S.N</th>
				<th>applicants</th>
				<th>applied on</th>
				<th>download cv</th>
			</tr>
		</thead>
		<tbody>
			{% for application in jobobject.jobapplication_set.all %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{application.jobseeker}}</td>
				<td>{{application.created_at}}</td>
				<td>
					<a href="{{application.jobseeker.cv.url}}" download>Download CV</a>
					<a href="{{application.cover_letter.url}}" download>Download Coverletter</a>

				</td>
				


			</tr>
			{% endfor %}
			

		</tbody>
		



	</table>

{% endblock %}

templates/employertemplates/employerprofile.html
{% extends 'employertemplates/employerbase.html' %}
[% load static %}
{% block content %}
<br>
<h4>Employer_name:{{employers.name}}</h4>
<h4>phone:{{employers.mobile}}</h4>
<h4>Email:{{employers.email}}</h4>
<h4>Websites:{{employers.website}}</h4>


<h3>job posted by:{{employers.company}}</h3>
<hr>

<table class="table">
	<thead>
		<tr>
			<th>S.N</th>
			<th>Job_title</th>
			<th>Deadline</th>
			<th>Posted on</th>
			


		</tr>
		
	</thead>
	<tbody>
			{% for job in employers.job_set.all %}
		 		<tr>
		 			<td>{{forloop.counter}}</td>
		 			<td><a href="{% url 'jobapp:employerjobdetail' job.id %}">{{job.title}}({{job.jobapplication_set.count}} applications)</a></td>
		 			<td>{{job.deadline}}</td>
		 			<td>{{job.created_at}}</td>

		 		</tr>
	 		{% endfor %}
 	
 		

 	</tbody>
	
	

</table>
{% endblock %}

templates/employertemplates/employerregistration.html
{% extends 'employertemplates/employerbase.html' %}
{% load static %}
{% block content %}
<h2>Employer Registration</h2>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-info">register</button>
	

</form>
{% endblock %}