jobapp/urls.py
from django.urls import path
from .views import *

app_name = 'jobapp'

urlpatterns = [
    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('job-admin/hello/', AdminHomeHelloView.as_view(), name='adminhomehello'),
    path('jobseeker/<int:pk>/details/',
         JobSeekerDetailView.as_view(), name='jobseekerdetail'),
    path('jobseeker/registration/', JobSeekerRegistration.as_view(),
         name='jobseekerregistration'),
    path('job/<int:pk>/apply/', JobSeekerApplyView.as_view(), name="jobapply"),
    path("login/", LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    # path('employer/registration/', EmployerRegistrationView.as_view(),
    #      name='employerregistration'),
    path('employer/myprofile/', EmployerProfileView.as_view(),
         name='employerprofile'),
    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),
    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),
    path('employer/registration/', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/profile/',AdminProfileView.as_view(),name = 'adminprofile'),





]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("jobapp.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
	<!-- bootstrap css -->
    <link href="{% static 'jobseekerstatic/css/style.css' %}" rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="{% static 'jobseekerstatic/css/font-awesome.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <a class="navbar-brand" href="{% url 'jobapp:adminhome' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'jobapp:adminprofile' %}">myprofile<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="#"></a>
      <h7>logged in as {{request.user}}</h7>
      <a class="nav-item nav-link active navbar-right" href="{% url 'jobapp:logout' %}">logout</a>

    </div>
  </div>
</nav>    

{% block content %}
{% endblock %}
   

{% block js %}
{% endblock %}
</body>
</html>

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
[% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">

{% endblock %}
{% block content %}
<p>this is home</p>
<div class="row">
	<div class='col-md-3 bg-success p-3'>
				<h3 class='text-center text-white'>{{allemployers.count}}</h3>
				<h4 class='text-center'>Employers</h4>

				

				
	</div>
	<div class="col-md-3 bg-warning p-3">
				<h3 class='text-center text-white'>{{alljobs.count}}</h3>
				<h4 class='text-center'>Jobs</h4>
				
				
			
		
	</div>
	<div class="col-md-3 bg-info p-3">
		
				<h3 class='text-center text-white'>{{alljobseekers.count}}</h3>
				<h4 class='text-center'>Jobseekers</h4>
				
		
		
	</div>
	<div class="col-md-3 bg-danger p-3">
 
				<h3 class='text-center text-white'>{{allapplications.count}}</h3>
				<h4 class='text-center'>Applications</h4>
				
			
	</div>
	

</div>
<!-----------------------------------------listview of employer and jobseekers------------>
<table class="table">
	<thead>
		<tr>
			<th>S.N</th>
			<!-- <th>Employer</th> -->
			<th>Jobseeker</th>
		</tr>		
	</thead>
	<tbody>
		{% for list in alljobseekers.jobapplication_set.all %}
 		<tr>
 			<td>{{ forloop.counter }}</td>
 			<td>{{ list.jobseeker.address }}</td>
 			

 		</tr>
 		{% endfor %}
 		

	</tbody>
	

</table>



<!-- chart.js -->
<div class="row">
	<div class="col-md-6">
		<canvas id="myChart" width="400" height="400"></canvas>

	</div>
</div>

{% endblock %}
{% block js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js">	
</script>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ['employers', 'jobs','jobseekers', 'jobapplications'],
        datasets: [{
            label: 'job statistics',
            data: [{{allemployers.count}},{{alljobs.count}},{{alljobseekers.count}}, {{allapplications.count}}],
            backgroundColor: [
            	'#33FF5B',
            	'#5B33FF',
            	'#5B33FF',
            	'#33FF5B',

                // 'rgba(255, 99, 132, 0.2)',
                // 'rgba(54, 162, 235, 0.2)',
                // 'rgba(255, 206, 86, 0.2)',
                // 'rgba(75, 192, 192, 0.2)',
               
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endblock %}

templates/admintemplates/adminhomehello.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

</body>
</html>

templates/admintemplates/adminprofile.html
{% extends 'admintemplates/adminbase.html' %}
[% load static %}
{% block content %}
<h2>My profile</h2>
<li>{{ admin.user }}</li>
<li>{{ admin.mobile }}</li>
<li>{{ admin.email }}</li>
<li>{{ admin.address }}</li>
<li>{{ admin.name }}</li>
<table class="table">
	<thead>
		<tr>
			<th>S.N</th>
			<!-- <th>Employer</th> -->
			<th>Jobseeker</th>
		</tr>		
	</thead>
	<tbody>
		{% for list in alljobseekers.jobapplication_set.all %}
 		<tr>
 			<td>{{ forloop.counter }}</td>
 			<td>{{ list.jobseeker.address }}</td>
 			

 		</tr>
 		{% endfor %}
 		

	</tbody>
	

</table>


{% endblock %}