jobapp/urls.py
from django.urls import path
from .views import *

app_name = 'jobapp'

urlpatterns = [
    path('', JobSeekerHomeView.as_view(), name='jobseekerhome'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('job-admin/hello/', AdminHomeHelloView.as_view(), name='adminhomehello'),
    path('jobseeker/<int:pk>/details/',
         JobSeekerDetailView.as_view(), name='jobseekerdetail'),
    path('jobseeker/registration/', JobSeekerRegistration.as_view(),
         name='jobseekerregistration'),
    path('job/<int:pk>/apply/', JobSeekerApplyView.as_view(), name="jobapply"),
    path("login/", LoginView.as_view(), name='login'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    # path('employer/registration/', EmployerRegistrationView.as_view(),
    #      name='employerregistration'),
    path('employer/myprofile/', EmployerProfileView.as_view(),
         name='employerprofile'),
    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),
    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),
    path('employer/registration/', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/profile/',AdminProfileView.as_view(),name = 'adminprofile'),





]

jobproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("jobapp.urls")),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/jobseekertemplates/jobseekerbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Dental Health Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

  
	
	<!-- css files -->
    <link href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' /><!-- bootstrap css -->
    <link href="{% static 'jobseekerstatic/css/style.css' %}" rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="{% static 'jobseekerstatic/css/font-awesome.css' %}" rel="stylesheet"><!-- fontawesome css -->
	<!-- //css files -->
	
	<!-- google fonts -->
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext" rel="stylesheet">
	<!-- //google fonts -->
	
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand" href="#">MyJob</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'jobapp:jobseekerhome' %}">CurrentJob<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="#">Top Jobs</a>
      <!-- <a class="nav-item nav-link active" href="#"></a> -->
      {% if request.user.is_authenticated and request.user.groups.first.name == "jobseeker" %}
       <h5>logged in as:{{request.user}}</h5>
       <h5><a href="{% url 'jobapp:jobseekerprofile' %}">myprofile</a></h5>
       
      {% else %}
        <a href="{% url 'jobapp:login' %}">login</a>
        <a class="nav-item nav-link active" href="{% url 'jobapp:jobseekerregistration' %}">Register1</a>
        
      {% endif %}  



    </div>
  </div>
</nav>
<div class="row">
    <div class="col-md-9">
        {% block content %}
        {% endblock %}
        

    </div>
    <div class="col-md-3">
        <h1>Mostly recently viewed jobs</h1>
        
    </div>
</div>
    

</body>

templates/jobseekertemplates/jobseekerdetail.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% load static %}
{% block content %}
	<h3>Job_title : {{jobseekerdetails.title}}</h3>
	<h4>Job_category : {{jobseekerdetails.category}}</h4>
	<p><img src="{{jobseekerdetails.image.url}}" width="200px;"></p>
	<li>salary : {{jobseekerdetails.salary}}</li>
	<li>skills : {{jobseekerdetails.skills}}</li>
	<li>education : {{jobseekerdetails.education}}</li>
	<a href="{% url 'jobapp:jobapply' jobseekerdetails.id %}">Apply </a>
	<h2 class="text-success">This job has been viewed for {{jobseekerdetails.views_count}} times</h2>


{% endblock %}

templates/jobseekertemplates/jobseekerhome.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
[% load static %}
{% block content %}
<div class="row">
    {% for jobseeker in jobseekerlists %}	
	  <div class="col-sm-4">
	    <div class="card">
	      <div class="card-body">
	        <h5 class="card-title">{{jobseeker.title}}</h5>
	        <p class="card-text">{{jobseeker.details}}</p>
	        <a href="{% url 'jobapp:jobseekerdetail' jobseeker.id %}" class="btn btn-primary">view detail</a>
	      </div>
	    </div>
	  </div>
    {% endfor %}
  
</div>


{% endblock %}

templates/jobseekertemplates/jobseekerjobapply.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% load static %}
{% block content %}
<h3>Job Application Form</h3>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-info">Apply</button>
	

</form>
{% endblock %}

templates/jobseekertemplates/jobseekerlogin.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% load static %}
{% block content %}
<br>
<style type="text/css">
	.login{
			text-align: center;

	}
	

</style>

{% if error %}
	<li class="text-danger">{{error}}</li>
{% endif %}	
 <form method = "POST">
 	{% csrf_token %}
	 <div class="login">
	    <h1>Login</h1>	
	 	{{ form.as_p }}
	 	<button>Login</button>
	 </div>	

 </form>
 <h4>Don't have account?</h4>
 <p class="text-info"><a href="{% url 'jobapp:jobseekerregistration' %}">Register as Jobseeker</a></p>
 <br>

 <p class="text-info"><a href="{% url 'jobapp:employerregistration' %}">Register as employer</a></p>


{% endblock %}

templates/jobseekertemplates/jobseekerprofile.html
{% extends "jobseekertemplates/jobseekerbase.html" %}
{% load static %}
{% block content %}

 <h1>my profile</h1>
 <hr>
 <h4>Name:{{jobseeker.name}}</h4>
 <hr>
 <h3>Job i have applied</h3>
 <table class="table">
 	<thead>
 		<tr>
 			<th>S.N</th>
 			<th>Job_title</th>
 			<th>Company</th>
 			<th>Date</th>
 		</tr>
 		
 	</thead>
 	<tbody>
 		{% for jobappl in jobseeker.jobapplication_set.all %}
 		<tr>
 			<td>{{forloop.counter}}</td>
 			<td>{{jobappl.job.title}}</td>
 			<td>{{jobappl.job.employer.company}}</td>
 			<td>{{jobappl.created_at}}</td>

 		</tr>
 		{% endfor %}
 		

 	</tbody>
 	

 </table>
{% endblock %}

templates/jobseekertemplates/jobseekerregistration.html
{% extends 'jobseekertemplates/jobseekerbase.html' %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button>register</button>	


</form>
{% endblock %}